version: '3'
volumes:
  dados:
networks:
  banco:
  web:
services:
  db:
    image: postgres:9.6
    volumes:
      # volume dos dados
      - dados:/var/lib/postgresq/data
      # Scripts
      - ./scripts:/scripts
      - ./scripts/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - banco
  frontend:
    image: nginx:1.13
    volumes:
      # Site
      - ./web:/usr/share/nginx/html/
      # Configuração do nginx
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - web
    depends_on:
      - app
    ports:
      - 80:80
  app:
    image: python:3.6
    volumes:
      - ./app:/app
    working_dir: /app
    command: bash ./app.sh
    networks:
      - banco
      - web
    depends_on:
      - db
